# Uppic 图片上传微服务
FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY . .

EXPOSE 3900

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3900"]
